import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', data: { breadcrumb: 'Home' }, loadComponent: () => import('./pages/overview-page').then(m => m.OverviewPage) },
  { path: 'getting-started', data: { breadcrumb: 'Getting Started' }, loadComponent: () => import('./pages/getting-started-page').then(m => m.GettingStartedPage) },
  { path: 'colors', data: { breadcrumb: 'Cores' }, loadComponent: () => import('./pages/colors-page').then(m => m.ColorsPage) },
  { path: 'typography', data: { breadcrumb: 'Tipografia' }, loadComponent: () => import('./pages/typography-page').then(m => m.TypographyPage) },
  { path: 'button', data: { breadcrumb: 'Button' }, loadComponent: () => import('./pages/button-page').then(m => m.ButtonPage) },
  { path: 'badge', data: { breadcrumb: 'Badge' }, loadComponent: () => import('./pages/badge-page').then(m => m.BadgePage) },
  { path: 'checkbox', data: { breadcrumb: 'Checkbox' }, loadComponent: () => import('./pages/checkbox-page').then(m => m.CheckboxPage) },
  { path: 'form-field', data: { breadcrumb: 'Form Field' }, loadComponent: () => import('./pages/form-field-page').then(m => m.FormFieldPage) },
  { path: 'switch', data: { breadcrumb: 'Switch' }, loadComponent: () => import('./pages/switch-page').then(m => m.SwitchPage) },
  { path: 'slider', data: { breadcrumb: 'Slider' }, loadComponent: () => import('./pages/slider-page').then(m => m.SliderPage) },
  { path: 'sidenav', data: { breadcrumb: 'Sidenav' }, loadComponent: () => import('./pages/sidenav-page').then(m => m.SidenavPage) },
  { path: 'breadcrumb', data: { breadcrumb: 'Breadcrumb' }, loadComponent: () => import('./pages/breadcrumb-page').then(m => m.BreadcrumbPage) },
  { path: 'toolbar', data: { breadcrumb: 'Toolbar' }, loadComponent: () => import('./pages/toolbar-page').then(m => m.ToolbarPage) },
  { path: 'alert', data: { breadcrumb: 'Alert' }, loadComponent: () => import('./pages/alert-page').then(m => m.AlertPage) },
  { path: 'snackbar', data: { breadcrumb: 'Snackbar' }, loadComponent: () => import('./pages/snackbar-page').then(m => m.SnackbarPage) },
  { path: 'progress', data: { breadcrumb: 'Progress' }, loadComponent: () => import('./pages/progress-page').then(m => m.ProgressPage) },
  { path: 'tabs', data: { breadcrumb: 'Tabs' }, loadComponent: () => import('./pages/tabs-page').then(m => m.TabsPage) },
  { path: 'accordion', data: { breadcrumb: 'Accordion' }, loadComponent: () => import('./pages/accordion-page').then(m => m.AccordionPage) },
  { path: 'radio', data: { breadcrumb: 'Radio' }, loadComponent: () => import('./pages/radio-page').then(m => m.RadioPage) },
  { path: 'select', data: { breadcrumb: 'Select' }, loadComponent: () => import('./pages/select-page').then(m => m.SelectPage) },
  { path: 'chip', data: { breadcrumb: 'Chip' }, loadComponent: () => import('./pages/chip-page').then(m => m.ChipPage) },
  { path: 'divider', data: { breadcrumb: 'Divider' }, loadComponent: () => import('./pages/divider-page').then(m => m.DividerPage) },
  { path: 'tooltip', data: { breadcrumb: 'Tooltip' }, loadComponent: () => import('./pages/tooltip-page').then(m => m.TooltipPage) },
  { path: 'dialog', data: { breadcrumb: 'Dialog' }, loadComponent: () => import('./pages/dialog-page').then(m => m.DialogPage) },
  { path: 'list', data: { breadcrumb: 'List' }, loadComponent: () => import('./pages/list-page').then(m => m.ListPage) },
  { path: 'table', data: { breadcrumb: 'Table' }, loadComponent: () => import('./pages/table-page').then(m => m.TablePage) },
  { path: 'paginator', data: { breadcrumb: 'Paginator' }, loadComponent: () => import('./pages/paginator-page').then(m => m.PaginatorPage) },
  { path: 'menu', data: { breadcrumb: 'Menu' }, loadComponent: () => import('./pages/menu-page').then(m => m.MenuPage) },
  { path: 'stepper', data: { breadcrumb: 'Stepper' }, loadComponent: () => import('./pages/stepper-page').then(m => m.StepperPage) },
  { path: 'datepicker', data: { breadcrumb: 'Datepicker' }, loadComponent: () => import('./pages/datepicker-page').then(m => m.DatepickerPage) },
  { path: 'tree', data: { breadcrumb: 'Tree' }, loadComponent: () => import('./pages/tree-page').then(m => m.TreePage) },
  { path: 'page-summary', data: { breadcrumb: 'Page Summary' }, loadComponent: () => import('./pages/page-summary-page').then(m => m.PageSummaryPage) },
  { path: 'theming', data: { breadcrumb: 'Theming' }, loadComponent: () => import('./pages/theming-page').then(m => m.ThemingPage) },
  { path: '**', redirectTo: '' },
];
